// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64
	AuthorID    int64
	Slug        string
	Title       string
	Description string
	Body        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ArticleTag struct {
	ArticleID int64
	TagID     int64
}

type Comment struct {
	ID        int64
	Body      string
	AuthorID  int64
	ArticleID int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Favorite struct {
	UserID    int64
	ArticleID int64
}

type Follow struct {
	FollowerID  int64
	FollowingID int64
}

type Tag struct {
	ID   int64
	Name string
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Bio       pgtype.Text
	Image     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
