// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64
	AuthorID    int64
	Slug        string
	Title       string
	Description string
	Body        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Comment struct {
	ID        int64
	Body      string
	AuthorID  int64
	ArticleID int64
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Pwd       string
	Bio       pgtype.Text
	Img       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
